name: CI/CD Pipeline that builds and Pushes Docker image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Pipeline
        run: python run.py

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/test_iris_cicd:latest

      # - name: Run Docker container
      #   run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/test_iris_cicd:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test_iris_cicd:latest
        
      
      # # another way to build and push docker image to docker hub
      # - name: Build and Push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: DockerFileFolder/ # uses when your Dockerfile inside folder(pass that folder path)
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/test_iris_cicd:latest
